-- migrate:up
create table households
(
	id   bigint primary key generated by default as identity,
	name text not null
);

create table household_users
(
	household_id bigint not null references households (id),
	user_id      bigint not null references users (id),
	primary key (household_id, user_id)
);

-- migrate:down
drop table household_users;
drop table households;
