-- migrate:up
create table users
(
	id                      bigint primary key generated by default as identity,
	name                    text    not null,
	email                   text    not null,
	password_hash           text    not null,
	password_hash_algorithm text    not null,
	is_activated            boolean not null default false,
	is_superuser            boolean not null default false,
	unique (email)
);

create table recipes
(
	id                   bigint primary key generated by default as identity,
	name                 text        not null,            -- Name des Rezeptes, verpflichtend
	description          text        not null default '', -- optionale Beschreibung, aber per default einfach leer.
	working_time         interval    null,                -- Zubereitungszeit
	waiting_time         interval    null,                -- Wartezeit
	created_at           timestamptz not null default now(),
	updated_at           timestamptz null,
	created_by           bigint      not null
		references users (id)
			on delete cascade,
	source               text        null,                -- Quelle, falls das Rezept von woanders importiert wurde. Kann ne URL oder ein Buch oder so sein.
	servings             int         not null default 1,  -- Anzahl der Portionen
	servings_description text        not null default '', -- Beschreibung für die Portionsangabe, etwa für "1 Laib Brot" oder so.
	unique (name)
);

create table steps
(
	id          bigint primary key generated by default as identity,
	recipe_id   bigint   not null
		references recipes (id)
			on delete cascade,
	sort_order  integer  not null default 1, -- Parameter zum Sortieren der Schritte
	instruction text     not null,           -- Die eigentliche Angabe, was zu tun ist.
	time        interval null                -- Angabe, wie lange dies dauert, optional
);

-- Liste aller potenziellen Zutaten
create table foods
(
	id   bigint primary key generated by default as identity,
	name text not null,
	unique (name)
);

-- Liste der Einheiten
create table units
(
	id   bigint primary key generated by default as identity,
	name text not null,
	unique (name)
);

-- Liste der Zutaten pro Schritt. Die Gesamtzutaten für ein Rezept ist einfach
-- die Liste aller Zutaten aller Schritte kombiniert.
create table step_ingredients
(
	step_id bigint  not null
		references steps (id)
			on delete cascade,
	food_id bigint  not null
		references foods (id)
			on delete restrict,
	unit_id bigint  null
		references units (id)
			on delete restrict,
	amount  numeric not null default 0,
	note    text    not null default ''
);


-- migrate:down
drop table step_ingredients;
drop table units;
drop table foods;
drop table steps;
drop table recipes;
drop table users;
