-- migrate:up
create table users
(
	id                      bigint primary key generated by default as identity,
	name                    text    not null,
	email                   text    not null,
	password_hash           text    not null,
	password_hash_algorithm text    not null,
	is_activated            boolean not null default false,
	is_superuser            boolean not null default false,
	unique (email)
);

create table recipes
(
	id                   bigint primary key generated by default as identity,
	name                 text        not null,            -- name of the recipe, mandatory
	description          text        not null default '', -- optional description
	working_time         interval    null,
	waiting_time         interval    null,
	created_at           timestamptz not null default now(),
	updated_at           timestamptz null,
	created_by           bigint      not null
		references users (id)
			on delete cascade,
	source               text        null,                -- Source, if this recipe is copied/imported from elsewhere. URL or free-form text for books etc.
	servings             int         not null default 1,
	servings_description text        not null default '', -- description for servings, because "one portion bread" doesn't make sense.
	unique (name)
);

create table steps
(
	id          bigint primary key generated by default as identity,
	recipe_id   bigint   not null
		references recipes (id)
			on delete cascade,
	sort_order  integer  not null default 1, -- used for sorting the steps
	instruction text     not null,
	time        interval null
);

create table ingredients
(
	id   bigint primary key generated by default as identity,
	name text not null,
	unique (name)
);

create table units
(
	id   bigint primary key generated by default as identity,
	name text not null,
	unique (name)
);

-- List of the ingredients per step. The total ingredients for one recipe
-- is the sum of all step ingredients.
create table step_ingredients
(
	step_id        bigint  not null
		references steps (id)
			on delete cascade,
	ingredients_id bigint  not null
		references ingredients (id)
			on delete restrict,
	unit_id        bigint  null
		references units (id)
			on delete restrict,
	amount         numeric not null default 0,
	note           text    not null default ''
);


-- migrate:down
drop table step_ingredients;
drop table units;
drop table ingredients;
drop table steps;
drop table recipes;
drop table users;
