// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: ingredients.sql

package queries

import (
	"context"
)

const getAllIngredients = `-- name: GetAllIngredients :many
select name
from ingredients
order by id
`

func (q *Queries) GetAllIngredients(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
