// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package queries

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type Household struct {
	ID   int64
	Name string
}

type HouseholdUser struct {
	HouseholdID int64
	UserID      int64
}

type Ingredient struct {
	ID   int64
	Name string
}

type Recipe struct {
	ID                  int64
	Name                string
	Description         string
	WorkingTime         pgtype.Interval
	WaitingTime         pgtype.Interval
	CreatedAt           time.Time
	UpdatedAt           sql.NullTime
	CreatedBy           int64
	Source              sql.NullString
	Servings            int32
	ServingsDescription string
}

type SchemaMigration struct {
	Version string
}

type Step struct {
	ID          int64
	RecipeID    int64
	SortOrder   int32
	Instruction string
	Time        pgtype.Interval
}

type StepIngredient struct {
	StepID        int64
	IngredientsID int64
	UnitID        sql.NullInt64
	Amount        pgtype.Numeric
	Note          string
}

type Unit struct {
	ID   int64
	Name string
}

type User struct {
	ID                    int64
	Name                  string
	Email                 string
	PasswordHash          string
	PasswordHashAlgorithm string
	IsActivated           bool
	IsSuperuser           bool
}
