// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: query.sql

package queries

import (
	"context"
)

const exampleQuery = `-- name: ExampleQuery :one
select 1
`

func (q *Queries) ExampleQuery(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, exampleQuery)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}
